import json
from operator import itemgetter

# Sample data input (replace with actual data reading if needed)
data = [
{"Image": "./judiciary/frame_1493.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8136},
{"Image": "./judiciary/frame_1487.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8546},
{"Image": "./judiciary/frame_1478.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8679},
{"Image": "./judiciary/frame_7586.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8938},
{"Image": "./judiciary/frame_7592.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8968},
{"Image": "./judiciary/frame_7545.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8468},
{"Image": "./judiciary/frame_7551.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9008},
{"Image": "./judiciary/frame_4070.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8649},
{"Image": "./judiciary/frame_7579.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8529},
{"Image": "./judiciary/frame_0216.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8665},
{"Image": "./judiciary/frame_4058.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5090},
{"Image": "./judiciary/frame_0202.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8202},
{"Image": "./judiciary/frame_4064.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8262},
{"Image": "./judiciary/frame_1929.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7544},
{"Image": "./judiciary/frame_0389.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8937},
{"Image": "./judiciary/frame_7431.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5548},
{"Image": "./judiciary/frame_3870.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7221},
{"Image": "./judiciary/frame_0362.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8191},
{"Image": "./judiciary/frame_0404.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8779},
{"Image": "./judiciary/frame_0410.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8934},
{"Image": "./judiciary/frame_7419.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5260},
{"Image": "./judiciary/frame_0376.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8497},
{"Image": "./judiciary/frame_0606.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8205},
{"Image": "./judiciary/frame_0160.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7295},
{"Image": "./judiciary/frame_0612.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8470},
{"Image": "./judiciary/frame_0174.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7864},
{"Image": "./judiciary/frame_0613.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8608},
{"Image": "./judiciary/frame_0175.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7905},
{"Image": "./judiciary/frame_0607.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9121},
{"Image": "./judiciary/frame_0161.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7090},
{"Image": "./judiciary/frame_0411.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8687},
{"Image": "./judiciary/frame_7418.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5618},
{"Image": "./judiciary/frame_0377.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8748},
{"Image": "./judiciary/frame_0363.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8635},
{"Image": "./judiciary/frame_0405.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8820},
{"Image": "./judiciary/frame_7430.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6338},
{"Image": "./judiciary/frame_4887.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5287},
{"Image": "./judiciary/frame_3865.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6787},
{"Image": "./judiciary/frame_1928.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7620},
{"Image": "./judiciary/frame_3871.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6086},
{"Image": "./judiciary/frame_0388.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8076},
{"Image": "./judiciary/frame_7395.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5347},
{"Image": "./judiciary/frame_4071.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8933},
{"Image": "./judiciary/frame_0203.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8569},
{"Image": "./judiciary/frame_0217.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8891},
{"Image": "./judiciary/frame_7578.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8029},
{"Image": "./judiciary/frame_1647.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5120},
{"Image": "./judiciary/frame_7550.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8539},
{"Image": "./judiciary/frame_7544.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8474},
{"Image": "./judiciary/frame_4059.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6062},
{"Image": "./judiciary/frame_7593.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8957},
{"Image": "./judiciary/frame_7587.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9021},
{"Image": "./judiciary/frame_4930.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8179},
{"Image": "./judiciary/frame_1479.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8426},
{"Image": "./judiciary/frame_1486.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8484},
{"Image": "./judiciary/frame_1492.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8807},
{"Image": "./judiciary/frame_1484.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8612},
{"Image": "./judiciary/frame_1490.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8750},
{"Image": "./judiciary/frame_7591.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9045},
{"Image": "./judiciary/frame_0598.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8306},
{"Image": "./judiciary/frame_7585.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8795},
{"Image": "./judiciary/frame_7552.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8729},
{"Image": "./judiciary/frame_0229.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8991},
{"Image": "./judiciary/frame_7546.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8196},
{"Image": "./judiciary/frame_0201.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8725},
{"Image": "./judiciary/frame_4067.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8795},
{"Image": "./judiciary/frame_4073.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8524},
{"Image": "./judiciary/frame_0215.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8347},
{"Image": "./judiciary/frame_7397.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5369},
{"Image": "./judiciary/frame_0349.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8417},
{"Image": "./judiciary/frame_7426.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5237},
{"Image": "./judiciary/frame_3867.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5374},
{"Image": "./judiciary/frame_3873.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6761},
{"Image": "./judiciary/frame_7432.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6993},
{"Image": "./judiciary/frame_0375.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8698},
{"Image": "./judiciary/frame_0413.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8614},
{"Image": "./judiciary/frame_0407.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8661},
{"Image": "./judiciary/frame_0361.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8641},
{"Image": "./judiciary/frame_1043.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5728},
{"Image": "./judiciary/frame_0188.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8443},
{"Image": "./judiciary/frame_0639.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8501},
{"Image": "./judiciary/frame_0611.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8109},
{"Image": "./judiciary/frame_0177.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7839},
{"Image": "./judiciary/frame_0163.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8712},
{"Image": "./judiciary/frame_0605.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8695},
{"Image": "./judiciary/frame_0604.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8795},
{"Image": "./judiciary/frame_0162.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8014},
{"Image": "./judiciary/frame_0610.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8729},
{"Image": "./judiciary/frame_0176.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8266},
{"Image": "./judiciary/frame_0638.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8648},
{"Image": "./judiciary/frame_0189.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8251},
{"Image": "./judiciary/frame_0360.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8718},
{"Image": "./judiciary/frame_0406.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8684},
{"Image": "./judiciary/frame_0374.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7723},
{"Image": "./judiciary/frame_0412.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8544},
{"Image": "./judiciary/frame_6063.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5392},
{"Image": "./judiciary/frame_7433.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5522},
{"Image": "./judiciary/frame_7427.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5964},
{"Image": "./judiciary/frame_0348.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7933},
{"Image": "./judiciary/frame_3872.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5881},
{"Image": "./judiciary/frame_3866.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5704},
{"Image": "./judiciary/frame_1042.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5449},
{"Image": "./judiciary/frame_4066.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7355},
{"Image": "./judiciary/frame_4072.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8600},
{"Image": "./judiciary/frame_0214.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8529},
{"Image": "./judiciary/frame_0200.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8214},
{"Image": "./judiciary/frame_0228.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8600},
{"Image": "./judiciary/frame_7547.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8366},
{"Image": "./judiciary/frame_7553.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8521},
{"Image": "./judiciary/frame_6895.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5083},
{"Image": "./judiciary/frame_7584.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8909},
{"Image": "./judiciary/frame_7590.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8820},
{"Image": "./judiciary/frame_0599.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8613},
{"Image": "./judiciary/frame_1491.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8652},
{"Image": "./judiciary/frame_1485.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8302},
{"Image": "./judiciary/frame_1481.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8711},
{"Image": "./judiciary/frame_1495.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8407},
{"Image": "./judiciary/frame_4089.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8887},
{"Image": "./judiciary/frame_7594.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8589},
{"Image": "./judiciary/frame_7580.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8941},
{"Image": "./judiciary/frame_0204.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8420},
{"Image": "./judiciary/frame_4076.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8203},
{"Image": "./judiciary/frame_0210.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8932},
{"Image": "./judiciary/frame_0238.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8429},
{"Image": "./judiciary/frame_7557.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9306},
{"Image": "./judiciary/frame_7543.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8573},
{"Image": "./judiciary/frame_3876.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5109},
{"Image": "./judiciary/frame_0416.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8305},
{"Image": "./judiciary/frame_0370.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8549},
{"Image": "./judiciary/frame_0364.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8890},
{"Image": "./judiciary/frame_0402.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8724},
{"Image": "./judiciary/frame_0358.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8353},
{"Image": "./judiciary/frame_3889.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6762},
{"Image": "./judiciary/frame_0199.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8673},
{"Image": "./judiciary/frame_0172.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8260},
{"Image": "./judiciary/frame_0614.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8344},
{"Image": "./judiciary/frame_0600.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8725},
{"Image": "./judiciary/frame_0166.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8503},
{"Image": "./judiciary/frame_0628.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8952},
{"Image": "./judiciary/frame_0629.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8894},
{"Image": "./judiciary/frame_0601.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8799},
{"Image": "./judiciary/frame_0167.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8508},
{"Image": "./judiciary/frame_0173.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8334},
{"Image": "./judiciary/frame_0615.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8653},
{"Image": "./judiciary/frame_0198.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8458},
{"Image": "./judiciary/frame_0359.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8716},
{"Image": "./judiciary/frame_7436.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5863},
{"Image": "./judiciary/frame_3888.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7166},
{"Image": "./judiciary/frame_0365.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8482},
{"Image": "./judiciary/frame_0403.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8726},
{"Image": "./judiciary/frame_0417.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8359},
{"Image": "./judiciary/frame_0371.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8340},
{"Image": "./judiciary/frame_7542.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8743},
{"Image": "./judiciary/frame_3877.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6006},
{"Image": "./judiciary/frame_0239.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8426},
{"Image": "./judiciary/frame_7556.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8990},
{"Image": "./judiciary/frame_4077.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8034},
{"Image": "./judiciary/frame_0211.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8574},
{"Image": "./judiciary/frame_4063.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8183},
{"Image": "./judiciary/frame_0205.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8701},
{"Image": "./judiciary/frame_7581.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9031},
{"Image": "./judiciary/frame_4088.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7770},
{"Image": "./judiciary/frame_7595.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8502},
{"Image": "./judiciary/frame_1494.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8362},
{"Image": "./judiciary/frame_1480.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8705},
{"Image": "./judiciary/frame_1496.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8424},
{"Image": "./judiciary/frame_1482.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8497},
{"Image": "./judiciary/frame_7583.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9132},
{"Image": "./judiciary/frame_7597.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8975},
{"Image": "./judiciary/frame_4920.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7796},
{"Image": "./judiciary/frame_4075.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8603},
{"Image": "./judiciary/frame_7568.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8643},
{"Image": "./judiciary/frame_0213.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8819},
{"Image": "./judiciary/frame_0207.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8714},
{"Image": "./judiciary/frame_7540.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8693},
{"Image": "./judiciary/frame_6892.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5097},
{"Image": "./judiciary/frame_7554.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8762},
{"Image": "./judiciary/frame_1938.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7727},
{"Image": "./judiciary/frame_3875.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5178},
{"Image": "./judiciary/frame_0398.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8845},
{"Image": "./judiciary/frame_0401.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8415},
{"Image": "./judiciary/frame_0367.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8366},
{"Image": "./judiciary/frame_0373.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8493},
{"Image": "./judiciary/frame_0415.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7813},
{"Image": "./judiciary/frame_7434.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5312},
{"Image": "./judiciary/frame_0165.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7979},
{"Image": "./judiciary/frame_0603.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8841},
{"Image": "./judiciary/frame_0617.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8442},
{"Image": "./judiciary/frame_0171.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8300},
{"Image": "./judiciary/frame_0159.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6847},
{"Image": "./judiciary/frame_0616.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7872},
{"Image": "./judiciary/frame_0170.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8092},
{"Image": "./judiciary/frame_0602.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8903},
{"Image": "./judiciary/frame_0164.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8470},
{"Image": "./judiciary/frame_0372.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8399},
{"Image": "./judiciary/frame_0414.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8549},
{"Image": "./judiciary/frame_0366.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8914},
{"Image": "./judiciary/frame_0400.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8568},
{"Image": "./judiciary/frame_1044.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5333},
{"Image": "./judiciary/frame_0399.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8247},
{"Image": "./judiciary/frame_1939.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8303},
{"Image": "./judiciary/frame_7555.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8593},
{"Image": "./judiciary/frame_7541.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8845},
{"Image": "./judiciary/frame_7569.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8481},
{"Image": "./judiciary/frame_0206.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8949},
{"Image": "./judiciary/frame_4074.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8381},
{"Image": "./judiciary/frame_4060.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6812},
{"Image": "./judiciary/frame_0212.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8575},
{"Image": "./judiciary/frame_7596.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8748},
{"Image": "./judiciary/frame_7582.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9019},
{"Image": "./judiciary/frame_1483.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8518},
{"Image": "./judiciary/frame_1497.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8614},
{"Image": "./judiciary/frame_1382.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5284},
{"Image": "./judiciary/frame_0249.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8669},
{"Image": "./judiciary/frame_7526.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9012},
{"Image": "./judiciary/frame_7532.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8628},
{"Image": "./judiciary/frame_0275.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8789},
{"Image": "./judiciary/frame_0261.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9061},
{"Image": "./judiciary/frame_7491.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6087},
{"Image": "./judiciary/frame_7485.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5902},
{"Image": "./judiciary/frame_7446.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6064},
{"Image": "./judiciary/frame_0329.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8815},
{"Image": "./judiciary/frame_7452.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6025},
{"Image": "./judiciary/frame_0301.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8623},
{"Image": "./judiciary/frame_0315.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8845},
{"Image": "./judiciary/frame_0117.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5499},
{"Image": "./judiciary/frame_0102.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5933},
{"Image": "./judiciary/frame_0314.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8542},
{"Image": "./judiciary/frame_0300.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8010},
{"Image": "./judiciary/frame_7447.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6295},
{"Image": "./judiciary/frame_0328.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8230},
{"Image": "./judiciary/frame_7453.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5704},
{"Image": "./judiciary/frame_7484.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5481},
{"Image": "./judiciary/frame_7490.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6865},
{"Image": "./judiciary/frame_0260.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9048},
{"Image": "./judiciary/frame_0274.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9040},
{"Image": "./judiciary/frame_7533.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8943},
{"Image": "./judiciary/frame_0248.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8844},
{"Image": "./judiciary/frame_7527.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9136},
{"Image": "./judiciary/frame_0062.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6411},
{"Image": "./judiciary/frame_0089.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5156},
{"Image": "./judiciary/frame_0060.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5325},
{"Image": "./judiciary/frame_0289.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8431},
{"Image": "./judiciary/frame_7531.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9129},
{"Image": "./judiciary/frame_2449.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5099},
{"Image": "./judiciary/frame_7525.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8852},
{"Image": "./judiciary/frame_0262.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8504},
{"Image": "./judiciary/frame_0276.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8653},
{"Image": "./judiciary/frame_7519.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8784},
{"Image": "./judiciary/frame_7486.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6405},
{"Image": "./judiciary/frame_7492.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6258},
{"Image": "./judiciary/frame_7445.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5909},
{"Image": "./judiciary/frame_7451.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6338},
{"Image": "./judiciary/frame_7479.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5474},
{"Image": "./judiciary/frame_0316.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9047},
{"Image": "./judiciary/frame_0302.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8198},
{"Image": "./judiciary/frame_0100.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5494},
{"Image": "./judiciary/frame_0115.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5311},
{"Image": "./judiciary/frame_0883.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5196},
{"Image": "./judiciary/frame_0129.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5113},
{"Image": "./judiciary/frame_0303.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7263},
{"Image": "./judiciary/frame_7478.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6459},
{"Image": "./judiciary/frame_0317.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8208},
{"Image": "./judiciary/frame_7450.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5794},
{"Image": "./judiciary/frame_7493.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5699},
{"Image": "./judiciary/frame_7487.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6235},
{"Image": "./judiciary/frame_0277.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8673},
{"Image": "./judiciary/frame_7518.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8255},
{"Image": "./judiciary/frame_0263.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7788},
{"Image": "./judiciary/frame_7524.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8599},
{"Image": "./judiciary/frame_7530.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8569},
{"Image": "./judiciary/frame_0288.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8912},
{"Image": "./judiciary/frame_0075.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5918},
{"Image": "./judiciary/frame_1380.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5149},
{"Image": "./judiciary/frame_0059.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5146},
{"Image": "./judiciary/frame_0298.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8433},
{"Image": "./judiciary/frame_0267.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8749},
{"Image": "./judiciary/frame_7508.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8507},
{"Image": "./judiciary/frame_0273.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8826},
{"Image": "./judiciary/frame_7534.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9189},
{"Image": "./judiciary/frame_2458.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5202},
{"Image": "./judiciary/frame_7520.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9000},
{"Image": "./judiciary/frame_7483.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5553},
{"Image": "./judiciary/frame_7497.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5092},
{"Image": "./judiciary/frame_0313.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8668},
{"Image": "./judiciary/frame_7440.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5440},
{"Image": "./judiciary/frame_0307.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8219},
{"Image": "./judiciary/frame_7454.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6052},
{"Image": "./judiciary/frame_0105.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6233},
{"Image": "./judiciary/frame_0139.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5354},
{"Image": "./judiciary/frame_0104.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5032},
{"Image": "./judiciary/frame_0110.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5587},
{"Image": "./judiciary/frame_7455.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6171},
{"Image": "./judiciary/frame_7441.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6124},
{"Image": "./judiciary/frame_7469.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5967},
{"Image": "./judiciary/frame_0312.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8578},
{"Image": "./judiciary/frame_0306.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7101},
{"Image": "./judiciary/frame_7496.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5710},
{"Image": "./judiciary/frame_7482.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5610},
{"Image": "./judiciary/frame_7521.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8608},
{"Image": "./judiciary/frame_7535.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8835},
{"Image": "./judiciary/frame_0272.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8320},
{"Image": "./judiciary/frame_2465.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5100},
{"Image": "./judiciary/frame_0266.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8667},
{"Image": "./judiciary/frame_7509.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8543},
{"Image": "./judiciary/frame_0299.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8347},
{"Image": "./judiciary/frame_0058.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5077},
{"Image": "./judiciary/frame_0070.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5326},
{"Image": "./judiciary/frame_0072.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5538},
{"Image": "./judiciary/frame_0066.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5220},
{"Image": "./judiciary/frame_5491.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5779},
{"Image": "./judiciary/frame_0270.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8908},
{"Image": "./judiciary/frame_0264.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8999},
{"Image": "./judiciary/frame_7523.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8804},
{"Image": "./judiciary/frame_0258.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8697},
{"Image": "./judiciary/frame_7537.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8742},
{"Image": "./judiciary/frame_7494.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6598},
{"Image": "./judiciary/frame_7480.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5697},
{"Image": "./judiciary/frame_0304.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7702},
{"Image": "./judiciary/frame_0310.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8383},
{"Image": "./judiciary/frame_7457.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6140},
{"Image": "./judiciary/frame_0338.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8680},
{"Image": "./judiciary/frame_0112.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5211},
{"Image": "./judiciary/frame_0648.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7969},
{"Image": "./judiciary/frame_0649.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8459},
{"Image": "./judiciary/frame_0107.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5183},
{"Image": "./judiciary/frame_7442.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5347},
{"Image": "./judiciary/frame_0339.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8179},
{"Image": "./judiciary/frame_7456.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6613},
{"Image": "./judiciary/frame_0311.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8392},
{"Image": "./judiciary/frame_0305.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7653},
{"Image": "./judiciary/frame_7481.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6106},
{"Image": "./judiciary/frame_7495.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5639},
{"Image": "./judiciary/frame_0259.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8801},
{"Image": "./judiciary/frame_7536.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8965},
{"Image": "./judiciary/frame_7522.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8820},
{"Image": "./judiciary/frame_0265.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8540},
{"Image": "./judiciary/frame_2472.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5249},
{"Image": "./judiciary/frame_0271.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8889},
{"Image": "./judiciary/frame_0067.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5115},
{"Image": "./judiciary/frame_0073.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5807},
{"Image": "./judiciary/frame_0081.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5232},
{"Image": "./judiciary/frame_0056.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5336},
{"Image": "./judiciary/frame_0297.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8276},
{"Image": "./judiciary/frame_0283.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8601},
{"Image": "./judiciary/frame_0268.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8805},
{"Image": "./judiciary/frame_7507.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8772},
{"Image": "./judiciary/frame_7513.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8561},
{"Image": "./judiciary/frame_0254.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9040},
{"Image": "./judiciary/frame_0240.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8612},
{"Image": "./judiciary/frame_3985.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6971},
{"Image": "./judiciary/frame_7498.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5152},
{"Image": "./judiciary/frame_3826.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8489},
{"Image": "./judiciary/frame_7473.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5742},
{"Image": "./judiciary/frame_7467.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5868},
{"Image": "./judiciary/frame_0308.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8801},
{"Image": "./judiciary/frame_0320.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8579},
{"Image": "./judiciary/frame_0334.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8588},
{"Image": "./judiciary/frame_0644.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8582},
{"Image": "./judiciary/frame_0650.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8634},
{"Image": "./judiciary/frame_0651.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8415},
{"Image": "./judiciary/frame_0645.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8365},
{"Image": "./judiciary/frame_0335.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7839},
{"Image": "./judiciary/frame_0321.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8427},
{"Image": "./judiciary/frame_7466.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5737},
{"Image": "./judiciary/frame_0309.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8607},
{"Image": "./judiciary/frame_3827.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8057},
{"Image": "./judiciary/frame_0241.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8636},
{"Image": "./judiciary/frame_0255.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8746},
{"Image": "./judiciary/frame_7512.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8605},
{"Image": "./judiciary/frame_0269.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8609},
{"Image": "./judiciary/frame_0282.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8718},
{"Image": "./judiciary/frame_7506.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9063},
{"Image": "./judiciary/frame_0296.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8413},
{"Image": "./judiciary/frame_1413.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5494},
{"Image": "./judiciary/frame_0082.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5491},
{"Image": "./judiciary/frame_0280.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9013},
{"Image": "./judiciary/frame_0294.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8278},
{"Image": "./judiciary/frame_7510.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8645},
{"Image": "./judiciary/frame_0243.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8336},
{"Image": "./judiciary/frame_0257.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8829},
{"Image": "./judiciary/frame_7538.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8780},
{"Image": "./judiciary/frame_3986.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6021},
{"Image": "./judiciary/frame_3825.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8123},
{"Image": "./judiciary/frame_7464.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5083},
{"Image": "./judiciary/frame_7470.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6777},
{"Image": "./judiciary/frame_0337.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8253},
{"Image": "./judiciary/frame_7458.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6185},
{"Image": "./judiciary/frame_0323.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8580},
{"Image": "./judiciary/frame_0109.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5686},
{"Image": "./judiciary/frame_0647.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8326},
{"Image": "./judiciary/frame_0646.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8598},
{"Image": "./judiciary/frame_4346.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8616},
{"Image": "./judiciary/frame_0134.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5120},
{"Image": "./judiciary/frame_0322.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8483},
{"Image": "./judiciary/frame_7459.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6288},
{"Image": "./judiciary/frame_0336.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8379},
{"Image": "./judiciary/frame_7471.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6107},
{"Image": "./judiciary/frame_3824.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7992},
{"Image": "./judiciary/frame_0256.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8799},
{"Image": "./judiciary/frame_7539.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8494},
{"Image": "./judiciary/frame_0242.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7725},
{"Image": "./judiciary/frame_2455.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5015},
{"Image": "./judiciary/frame_7277.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5288},
{"Image": "./judiciary/frame_7511.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9058},
{"Image": "./judiciary/frame_0295.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8400},
{"Image": "./judiciary/frame_0281.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8595},
{"Image": "./judiciary/frame_0054.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5055},
{"Image": "./judiciary/frame_0068.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5605},
{"Image": "./judiciary/frame_0083.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5352},
{"Image": "./judiciary/frame_0087.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5080},
{"Image": "./judiciary/frame_0093.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6068},
{"Image": "./judiciary/frame_0078.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5546},
{"Image": "./judiciary/frame_0285.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8613},
{"Image": "./judiciary/frame_0291.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8438},
{"Image": "./judiciary/frame_0246.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8636},
{"Image": "./judiciary/frame_7529.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9047},
{"Image": "./judiciary/frame_0252.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8716},
{"Image": "./judiciary/frame_7515.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8533},
{"Image": "./judiciary/frame_3820.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7650},
{"Image": "./judiciary/frame_0332.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8654},
{"Image": "./judiciary/frame_7449.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5845},
{"Image": "./judiciary/frame_0326.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8458},
{"Image": "./judiciary/frame_7461.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5574},
{"Image": "./judiciary/frame_7475.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6144},
{"Image": "./judiciary/frame_0642.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8392},
{"Image": "./judiciary/frame_0118.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5324},
{"Image": "./judiciary/frame_0643.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8435},
{"Image": "./judiciary/frame_7474.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6606},
{"Image": "./judiciary/frame_7460.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5984},
{"Image": "./judiciary/frame_7448.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6037},
{"Image": "./judiciary/frame_0327.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8586},
{"Image": "./judiciary/frame_0333.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8530},
{"Image": "./judiciary/frame_3821.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5107},
{"Image": "./judiciary/frame_7514.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8306},
{"Image": "./judiciary/frame_0253.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8873},
{"Image": "./judiciary/frame_0247.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8683},
{"Image": "./judiciary/frame_7528.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8502},
{"Image": "./judiciary/frame_0290.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8118},
{"Image": "./judiciary/frame_0284.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8489},
{"Image": "./judiciary/frame_0092.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5440},
{"Image": "./judiciary/frame_1398.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5049},
{"Image": "./judiciary/frame_0084.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5018},
{"Image": "./judiciary/frame_4547.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5225},
{"Image": "./judiciary/frame_0292.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8593},
{"Image": "./judiciary/frame_0286.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8839},
{"Image": "./judiciary/frame_0251.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8722},
{"Image": "./judiciary/frame_0245.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7090},
{"Image": "./judiciary/frame_0279.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8780},
{"Image": "./judiciary/frame_7489.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6191},
{"Image": "./judiciary/frame_7516.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8650},
{"Image": "./judiciary/frame_3823.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8087},
{"Image": "./judiciary/frame_0325.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8429},
{"Image": "./judiciary/frame_0331.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8568},
{"Image": "./judiciary/frame_7476.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6481},
{"Image": "./judiciary/frame_0319.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8490},
{"Image": "./judiciary/frame_7462.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5946},
{"Image": "./judiciary/frame_0641.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8239},
{"Image": "./judiciary/frame_0640.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8369},
{"Image": "./judiciary/frame_7463.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6285},
{"Image": "./judiciary/frame_7477.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6105},
{"Image": "./judiciary/frame_0318.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8062},
{"Image": "./judiciary/frame_0330.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8324},
{"Image": "./judiciary/frame_0324.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8896},
{"Image": "./judiciary/frame_7488.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6663},
{"Image": "./judiciary/frame_3822.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8073},
{"Image": "./judiciary/frame_7517.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8118},
{"Image": "./judiciary/frame_0278.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8474},
{"Image": "./judiciary/frame_0244.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8274},
{"Image": "./judiciary/frame_0250.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8538},
{"Image": "./judiciary/frame_0287.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8450},
{"Image": "./judiciary/frame_0293.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8739},
{"Image": "./judiciary/frame_1364.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5077},
{"Image": "./judiciary/frame_4546.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5350},
{"Image": "./judiciary/frame_0091.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5030},
{"Image": "./judiciary/frame_0035.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6222},
{"Image": "./judiciary/frame_4092.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8014},
{"Image": "./judiciary/frame_4086.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8125},
{"Image": "./judiciary/frame_7564.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8570},
{"Image": "./judiciary/frame_7570.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8725},
{"Image": "./judiciary/frame_4079.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8146},
{"Image": "./judiciary/frame_0237.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8641},
{"Image": "./judiciary/frame_7558.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9016},
{"Image": "./judiciary/frame_0223.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8672},
{"Image": "./judiciary/frame_0380.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8238},
{"Image": "./judiciary/frame_1920.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8059},
{"Image": "./judiciary/frame_3879.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5734},
{"Image": "./judiciary/frame_0394.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8748},
{"Image": "./judiciary/frame_1934.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7427},
{"Image": "./judiciary/frame_0419.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8435},
{"Image": "./judiciary/frame_7404.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5875},
{"Image": "./judiciary/frame_0343.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7879},
{"Image": "./judiciary/frame_3892.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6171},
{"Image": "./judiciary/frame_0357.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8520},
{"Image": "./judiciary/frame_3886.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7855},
{"Image": "./judiciary/frame_0182.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8180},
{"Image": "./judiciary/frame_0196.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7714},
{"Image": "./judiciary/frame_0169.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7888},
{"Image": "./judiciary/frame_0627.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8010},
{"Image": "./judiciary/frame_0141.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5619},
{"Image": "./judiciary/frame_0633.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8480},
{"Image": "./judiciary/frame_0632.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8744},
{"Image": "./judiciary/frame_0626.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8809},
{"Image": "./judiciary/frame_0140.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5101},
{"Image": "./judiciary/frame_0168.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8230},
{"Image": "./judiciary/frame_0197.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8774},
{"Image": "./judiciary/frame_0183.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8133},
{"Image": "./judiciary/frame_0356.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8329},
{"Image": "./judiciary/frame_7439.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5063},
{"Image": "./judiciary/frame_0342.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8851},
{"Image": "./judiciary/frame_3887.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7501},
{"Image": "./judiciary/frame_0424.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8421},
{"Image": "./judiciary/frame_3893.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8407},
{"Image": "./judiciary/frame_0418.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8431},
{"Image": "./judiciary/frame_1935.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7792},
{"Image": "./judiciary/frame_0381.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8412},
{"Image": "./judiciary/frame_0395.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8239},
{"Image": "./judiciary/frame_1921.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8218},
{"Image": "./judiciary/frame_0222.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8736},
{"Image": "./judiciary/frame_3878.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6025},
{"Image": "./judiciary/frame_0236.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8626},
{"Image": "./judiciary/frame_7559.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8572},
{"Image": "./judiciary/frame_4078.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8946},
{"Image": "./judiciary/frame_7571.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8364},
{"Image": "./judiciary/frame_7565.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8516},
{"Image": "./judiciary/frame_4087.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8912},
{"Image": "./judiciary/frame_4093.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8456},
{"Image": "./judiciary/frame_5399.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5380},
{"Image": "./judiciary/frame_0034.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5385},
{"Image": "./judiciary/frame_1499.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8348},
{"Image": "./judiciary/frame_5600.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5177},
{"Image": "./judiciary/frame_0036.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5545},
{"Image": "./judiciary/frame_4085.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8927},
{"Image": "./judiciary/frame_4091.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8268},
{"Image": "./judiciary/frame_1102.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5047},
{"Image": "./judiciary/frame_7598.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8340},
{"Image": "./judiciary/frame_7573.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8715},
{"Image": "./judiciary/frame_7567.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8447},
{"Image": "./judiciary/frame_0208.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8874},
{"Image": "./judiciary/frame_0220.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8737},
{"Image": "./judiciary/frame_0234.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8691},
{"Image": "./judiciary/frame_0397.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8589},
{"Image": "./judiciary/frame_1937.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8072},
{"Image": "./judiciary/frame_1923.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7962},
{"Image": "./judiciary/frame_0383.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8537},
{"Image": "./judiciary/frame_0368.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8940},
{"Image": "./judiciary/frame_0354.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8717},
{"Image": "./judiciary/frame_3885.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7635},
{"Image": "./judiciary/frame_0340.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8330},
{"Image": "./judiciary/frame_3891.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6713},
{"Image": "./judiciary/frame_0195.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8686},
{"Image": "./judiciary/frame_0181.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8386},
{"Image": "./judiciary/frame_0618.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8019},
{"Image": "./judiciary/frame_0630.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8657},
{"Image": "./judiciary/frame_0156.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5623},
{"Image": "./judiciary/frame_0142.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5348},
{"Image": "./judiciary/frame_0624.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8575},
{"Image": "./judiciary/frame_0143.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5860},
{"Image": "./judiciary/frame_0625.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8653},
{"Image": "./judiciary/frame_0631.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8800},
{"Image": "./judiciary/frame_0157.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5597},
{"Image": "./judiciary/frame_0619.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8317},
{"Image": "./judiciary/frame_2797.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5896},
{"Image": "./judiciary/frame_0180.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8340},
{"Image": "./judiciary/frame_0194.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8608},
{"Image": "./judiciary/frame_0355.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8919},
{"Image": "./judiciary/frame_3890.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6959},
{"Image": "./judiciary/frame_0341.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8560},
{"Image": "./judiciary/frame_0369.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8109},
{"Image": "./judiciary/frame_0382.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8270},
{"Image": "./judiciary/frame_1922.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7949},
{"Image": "./judiciary/frame_0396.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8417},
{"Image": "./judiciary/frame_1936.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8092},
{"Image": "./judiciary/frame_0235.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8447},
{"Image": "./judiciary/frame_0221.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8841},
{"Image": "./judiciary/frame_0209.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8665},
{"Image": "./judiciary/frame_7566.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.9022},
{"Image": "./judiciary/frame_7572.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8241},
{"Image": "./judiciary/frame_4090.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8256},
{"Image": "./judiciary/frame_7599.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8868},
{"Image": "./judiciary/frame_0037.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5752},
{"Image": "./judiciary/frame_3270.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5034},
{"Image": "./judiciary/frame_1473.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5507},
{"Image": "./judiciary/frame_1498.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8144},
{"Image": "./judiciary/frame_1488.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8880},
{"Image": "./judiciary/frame_0033.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6117},
{"Image": "./judiciary/frame_1477.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8270},
{"Image": "./judiciary/frame_4080.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8240},
{"Image": "./judiciary/frame_7589.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8945},
{"Image": "./judiciary/frame_4094.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8602},
{"Image": "./judiciary/frame_0225.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8911},
{"Image": "./judiciary/frame_0231.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8644},
{"Image": "./judiciary/frame_6654.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5109},
{"Image": "./judiciary/frame_0219.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8560},
{"Image": "./judiciary/frame_7576.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8340},
{"Image": "./judiciary/frame_7562.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8861},
{"Image": "./judiciary/frame_0392.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8433},
{"Image": "./judiciary/frame_1932.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8174},
{"Image": "./judiciary/frame_0386.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8467},
{"Image": "./judiciary/frame_1926.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8057},
{"Image": "./judiciary/frame_0437.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5416},
{"Image": "./judiciary/frame_0351.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8544},
{"Image": "./judiciary/frame_0345.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8220},
{"Image": "./judiciary/frame_3880.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5767},
{"Image": "./judiciary/frame_0423.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8324},
{"Image": "./judiciary/frame_7402.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5943},
{"Image": "./judiciary/frame_3894.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7936},
{"Image": "./judiciary/frame_0379.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8497},
{"Image": "./judiciary/frame_0190.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8224},
{"Image": "./judiciary/frame_0184.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8486},
{"Image": "./judiciary/frame_0635.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8668},
{"Image": "./judiciary/frame_0621.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8545},
{"Image": "./judiciary/frame_2778.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5134},
{"Image": "./judiciary/frame_7600.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8219},
{"Image": "./judiciary/frame_0609.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8310},
{"Image": "./judiciary/frame_0608.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8579},
{"Image": "./judiciary/frame_0620.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8765},
{"Image": "./judiciary/frame_0146.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6171},
{"Image": "./judiciary/frame_0634.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8745},
{"Image": "./judiciary/frame_0185.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7806},
{"Image": "./judiciary/frame_0191.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8682},
{"Image": "./judiciary/frame_0378.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8537},
{"Image": "./judiciary/frame_7403.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5677},
{"Image": "./judiciary/frame_0344.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8128},
{"Image": "./judiciary/frame_0422.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8015},
{"Image": "./judiciary/frame_3895.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7866},
{"Image": "./judiciary/frame_4888.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5860},
{"Image": "./judiciary/frame_0350.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8447},
{"Image": "./judiciary/frame_6906.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5074},
{"Image": "./judiciary/frame_0387.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8293},
{"Image": "./judiciary/frame_3881.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5077},
{"Image": "./judiciary/frame_1927.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7559},
{"Image": "./judiciary/frame_1933.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8045},
{"Image": "./judiciary/frame_0393.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8584},
{"Image": "./judiciary/frame_7563.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8932},
{"Image": "./judiciary/frame_7577.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8133},
{"Image": "./judiciary/frame_0218.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8603},
{"Image": "./judiciary/frame_0230.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8674},
{"Image": "./judiciary/frame_0224.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8968},
{"Image": "./judiciary/frame_4095.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8298},
{"Image": "./judiciary/frame_4081.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7991},
{"Image": "./judiciary/frame_7588.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8882},
{"Image": "./judiciary/frame_1476.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8812},
{"Image": "./judiciary/frame_1489.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8027},
{"Image": "./judiciary/frame_4083.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8927},
{"Image": "./judiciary/frame_4097.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5820},
{"Image": "./judiciary/frame_0232.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8382},
{"Image": "./judiciary/frame_0226.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8396},
{"Image": "./judiciary/frame_7549.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8859},
{"Image": "./judiciary/frame_6657.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5371},
{"Image": "./judiciary/frame_4068.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7964},
{"Image": "./judiciary/frame_7561.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8785},
{"Image": "./judiciary/frame_7575.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8258},
{"Image": "./judiciary/frame_1104.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5035},
{"Image": "./judiciary/frame_1925.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7884},
{"Image": "./judiciary/frame_0385.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8458},
{"Image": "./judiciary/frame_0391.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7319},
{"Image": "./judiciary/frame_7398.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5391},
{"Image": "./judiciary/frame_1931.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8322},
{"Image": "./judiciary/frame_1919.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8228},
{"Image": "./judiciary/frame_7429.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5365},
{"Image": "./judiciary/frame_0420.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8448},
{"Image": "./judiciary/frame_0346.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8381},
{"Image": "./judiciary/frame_3868.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6568},
{"Image": "./judiciary/frame_3897.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6699},
{"Image": "./judiciary/frame_0352.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8549},
{"Image": "./judiciary/frame_0434.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5147},
{"Image": "./judiciary/frame_0408.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8221},
{"Image": "./judiciary/frame_0187.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8481},
{"Image": "./judiciary/frame_0193.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8304},
{"Image": "./judiciary/frame_0144.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5324},
{"Image": "./judiciary/frame_0622.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8738},
{"Image": "./judiciary/frame_0636.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8580},
{"Image": "./judiciary/frame_0178.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8055},
{"Image": "./judiciary/frame_1500.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7672},
{"Image": "./judiciary/frame_0179.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8333},
{"Image": "./judiciary/frame_1501.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6615},
{"Image": "./judiciary/frame_0637.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8497},
{"Image": "./judiciary/frame_0145.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5027},
{"Image": "./judiciary/frame_0623.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8929},
{"Image": "./judiciary/frame_0192.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7651},
{"Image": "./judiciary/frame_0186.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8387},
{"Image": "./judiciary/frame_7400.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5490},
{"Image": "./judiciary/frame_0409.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8649},
{"Image": "./judiciary/frame_0353.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8728},
{"Image": "./judiciary/frame_0421.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8500},
{"Image": "./judiciary/frame_0347.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8162},
{"Image": "./judiciary/frame_3896.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7940},
{"Image": "./judiciary/frame_7428.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5359},
{"Image": "./judiciary/frame_3882.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5655},
{"Image": "./judiciary/frame_6905.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5085},
{"Image": "./judiciary/frame_7399.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5932},
{"Image": "./judiciary/frame_0390.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8365},
{"Image": "./judiciary/frame_3869.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.6290},
{"Image": "./judiciary/frame_0384.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7879},
{"Image": "./judiciary/frame_1105.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.5375},
{"Image": "./judiciary/frame_1924.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.7714},
{"Image": "./judiciary/frame_7574.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8497},
{"Image": "./judiciary/frame_4069.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8426},
{"Image": "./judiciary/frame_7560.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8895},
{"Image": "./judiciary/frame_0227.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8450},
{"Image": "./judiciary/frame_7548.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8235},
{"Image": "./judiciary/frame_0233.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8458},
{"Image": "./judiciary/frame_4082.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8061},
{"Image": "./judiciary/frame_1475.jpg", "Person": "Jerry Nadler", "Description": "Congressman", "Similarity": 0.8273}
]

# Sort data by similarity in descending order
sorted_data = sorted(data, key=itemgetter("Similarity"), reverse=True)

# Generate HTML content
html_content = """
<!DOCTYPE html>
<html>
<head>
    <title>Image Slider</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background-color: #f0f0f0;
        }
        #slider {
            width: 80%;
            height: 500px;
            position: relative;
            overflow: hidden;
            border: 1px solid #ddd;
            background-color: #fff;
            margin-bottom: 20px;
        }
        .slide {
            position: absolute;
            width: 100%;
            height: 100%;
            opacity: 0;
            background-size: cover;
            background-position: center;
        }
        .active {
            opacity: 1;
        }
        #imageRange {
            width: 80%;
        }
    </style>
</head>
<body>
    <div id="slider">
"""

for i, entry in enumerate(sorted_data):
    html_content += f"""
        <div class="slide" style="background-image: url('{entry['Image']}');">
            <p>{entry['Person']} - {entry['Description']} - Similarity: {entry['Similarity']}</p>
        </div>
    """

html_content += """
    </div>
    <input type="range" id="imageRange" min="0" max="{max_index}" value="0">

    <script>
        const slides = document.getElementsByClassName('slide');
        const slider = document.getElementById('imageRange');
        let currentIndex = 0;

        function showSlide(index) {
            for (let i = 0; i < slides.length; i++) {
                slides[i].classList.remove('active');
            }
            slides[index].classList.add('active');
        }

        slider.addEventListener('input', (event) => {
            currentIndex = parseInt(event.target.value, 10);
            showSlide(currentIndex);
        });

        // Initialize the slider
        showSlide(currentIndex);
    </script>
</body>
</html>
""".replace("{max_index}", str(len(sorted_data) - 1))

# Write the HTML content to a file
with open("slider.html", "w") as file:
    file.write(html_content)

print("HTML file generated: slider.html")
print("HTML file generated: slider.html")
